osx_image: xcode12.2
language: objective-c
sudo: required

cache:
    - bundler
    - cocoapods
    
before_install:
    - sh Scripts/Install_SwiftLint.sh
    - bundle install
    - bundle exec danger
    - sh Scripts/WatchSimulator-CoreText-Patch.sh
    - cd Samples && pod deintegrate && pod install --verbose

env:
    global:
    - LANG=en_US.UTF-8

    - WORKSPACE="Samples.xcworkspace"
    - IOS_SCHEME="iOS Sample"
    - IOS_SDK="iphonesimulator14.2"

    matrix:
    - DESTINATION="OS=14.2,name=iPhone 10" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME"

script:
    - travis_retry xcodebuild clean build test -scheme "$SCHEME" -workspace "$WORKSPACE" SDK="$IOS_SDK" -destination "$DESTINATION" -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
    - bash <(curl -s https://codecov.io/bash)
